$('#oneKeyInput').click(function(){
	$('#inputUserName').attr("value","");
    $('#userInputEmail').attr("value","");
    $('#inlineRadio1').prop("checked",true);
    $('#userInputPassword').attr("value","");
    $('#userInputPhone').attr("value","");
    $('#userInputAddress').attr("value","");
    
	$('#inputUserName').attr("value","王小明");
    $('#userInputEmail').attr("value","gn01046294@hotmail.com");
    $('#inlineRadio1').prop("checked",true);
    $('#userInputPassword').attr("value","Do!NG123");
    $('#userInputPhone').attr("value","0978334455");
    $('#userInputAddress').attr("value","台北市信義區信義路5段7號88樓");
});
$('#userReset').click(function(){
    $('#inputUserName').attr("value","");
    $('#userInputEmail').attr("value","");
    $('#inlineRadio1').prop("checked",false);
    $('#userInputPassword').attr("value","");
    $('#userInputPhone').attr("value","");
    $('#userInputAddress').attr("value","");
});